publish:
  docker:
    username: hq+docker@songsterr.com
    password: $$dockerhub_password
    email: hq+docker@songsterr.com
    repo: songsterr/woproject
    tag:
      - latest
      - $$COMMIT
    load: docker/image.tar
    file: Dockerfile
    save:
      destination: docker_cache.tar
      tag: latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true

cache:
  mount:
    - docker_cache.tar
